export const mockUsers = [
    { id: 1, title: 'Low-Fat Berry Blue Frozen Dessert', ingredients: 'blueberries, granulated sugar, vanilla yogurt, lemon juice', description:'Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.', icon_path:'', rating:'4.5', reviewCount:'4', instructions:'Toss 2 cups berries with sugar. Let stand for 45 minutes, stirring occasionally. Transfer b...', time:'PT24H45M'},
    { id: 2, title: 'Buttermilk Pie With Gingersnap Crumb Crust', ingredients: '"sugar", "margarine", "egg", "flour", "salt", "buttermilk", "graham cracker crumbs", "margarine"', description:'I copied this one out of a friends book so many moons ago that I cant remember where its from, bu...', icon_path:'', rating:'5', reviewCount:'23', instructions:'"Melt 1 1/2 ozs butter, add the flour and cook for 2 to 3 minutes, stirring.", "Gradually add milk...', time:'PT1H20M'},
    { id: 3, title: 'Biryani', ingredients: '"saffron", "milk", "hot green chili peppers", "onions", "garlic", "clove", "peppercorns", "cardamo...', description:'Make and share this Biryani recipe from Food.com.', icon_path:'', rating:'3', reviewCount:'1', instructions:'"Soak saffron in warm milk for 5 minutes and puree in blender.", "Add chiles, onions, ginger, garl...', time:'PT4H25M'},
    { id: 4, title: 'Best Lemonade', ingredients: '"sugar", "lemons, rind of", "lemon, zest of", "fresh water", "fresh lemon juice"', description:'This is from one of my first Good House Keeping cookbooks. You must use a *zester* in order to avo...', icon_path:'', rating:'4.5', reviewCount:'10', instructions:'"Into a 1 quart Jar with tight fitting lid, put sugar and lemon peel, or zest; add 1 1/2 cups ver...', time:'PT35M'},
    { id: 5, title: 'Carinas Tofu-Vegetable Kebabs', ingredients: '"extra firm tofu", "eggplant", "zucchini", "mushrooms", "soy sauce", "low sodium soy sauce", "oliv...', description:'This dish is best prepared a day in advance to allow the ingredients to soak in the marinade overni...', icon_path:'', rating:'4.5', reviewCount:'2', instructions:'"Drain the tofu, carefully squeezing out excess water, and pat dry with paper towels.", "Cut tofu...', time:'PT24H20M'},
    { id: 6, title: 'Cabbage Soup', ingredients: '"plain tomato juice", "cabbage", "onion", "carrots", "celery"', description:'Make and share this Cabbage Soup recipe from Food.com.', icon_path:'', rating:'4.5', reviewCount:'11', instructions:'"Mix everything together and bring to a boil.", "Reduce heat and simmer for 30 minutes (longer if ...', time:'PT50M'},
    { id: 7, title: 'Best Blackbottom Pie', ingredients: '"graham cracker crumbs", "sugar", "butter", "sugar", "cornstarch", "salt", "milk", "vanilla extrac...', description:'Make and share this Best Blackbottom Pie recipe from Food.com.', icon_path:'', rating:'1', reviewCount:'1', instructions:'"Graham Cracker Crust: In small bowl, combine graham cracker crumbs, sugar and butter. Press ev...', time:'PT2H20M'},
    { id: 8, title: 'Warm Chicken A La King', ingredients: '"chicken", "butter", "flour", "milk", "celery", "button mushrooms", "green pepper", "canned pimien...', description:'I copied this one out of a friends book so many moons ago that I cant remember where its from, bu...', icon_path:'', rating:'5', reviewCount:'23', instructions:'"Melt 1 1/2 ozs butter, add the flour and cook for 2 to 3 minutes, stirring.", "Gradually add milk...', time:'PT38M'},
    { id: 9, title: 'A Jad - Cucumber Pickle', ingredients: '"rice vinegar", "haeo"', description:'Make and share this A Jad - Cucumber Pickle recipe from Food.com.', icon_path:'', rating:'5', reviewCount:'2', instructions:'"Slice the cucumber in four lengthwise, then slice the pieces to segments about an eighth of an in...', time:'PT25M'},
    { id: 10, title: 'Boston Cream Pie', ingredients: '"margarine", "cake flour", "baking powder", "salt", "sugar", "vanilla", "eggs", "milk", "sugar"', description:'Make and share this Boston Cream Pie recipe from Food.com.', icon_path:'', rating:'2', reviewCount:'2', instructions:'"Beat egg whites until soft peaks form.", "Gradually add 1/2 cup sugar, beating until very stiff p...', time:'PT2H15M'}
  ];
  